/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AnswerCode = 'A' | 'B' | 'C' | 'D';

export const AnswerCode = {
    A: 'A' as AnswerCode,
    B: 'B' as AnswerCode,
    C: 'C' as AnswerCode,
    D: 'D' as AnswerCode
};

