package com.adaptionsoft.games.trivia.domain;

import com.adaptionsoft.games.trivia.domain.statemachine.State;

public enum PlayerState implements State {
    WAITING_FOR_DICE_ROLL,
    WAITING_FOR_ROLL_DICE_EVALUATION,
    IN_PENALTY_BOX,
    WAITING_TO_UPDATE_LOCATION,
    WAITING_TO_DRAW_1ST_QUESTION,
    WAITING_FOR_1ST_ANSWER,
    WAITING_FOR_1ST_ANSWER_EVALUATION,
    WAITING_TO_DRAW_2ND_QUESTION,
    WAITING_FOR_2ND_ANSWER,
    WAITING_FOR_2ND_ANSWER_EVALUATION,
    WAITING_TO_END_TURN_OR_GAME,
    WAITING_TO_VALIDATE_FIRST_CORRECT_ANSWER,
    WAITING_TO_VALIDATE_FIRST_INCORRECT_ANSWER,
    WAITING_TO_VALIDATE_SECOND_CORRECT_ANSWER,
    WAITING_TO_VALIDATE_SECOND_INCORRECT_ANSWER,
    WAITING_TO_VALIDATE_ODD_DICE_ROLL_FROM_PENALTY_BOX,
    WAITING_TO_VALIDATE_EVEN_DICE_ROLL_FROM_PENALTY_BOX,
    GAME_END,
}
