openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/games:
    get:
      tags:
      - game-controller
      operationId: listGames
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameResponseDto'
    post:
      tags:
      - game-controller
      operationId: createGame
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequestDto'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponseDto'
  /api/games/{gameId}:
    get:
      tags:
        - game-controller
      summary: get a game by its id
      operationId: getGameById
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "404":
          description: game not found
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Not Found
                status: 404
                instance: /games/777
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponseDto'
    delete:
      tags:
        - game-controller
      operationId: deleteGameById
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: No Content
  /api/games/{gameId}/players/{playerId}/join:
    post:
      tags:
      - game-controller
      operationId: addPlayerToGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: playerId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponseDto'
  /api/games/{gameId}/players/{playerId}/start:
    post:
      tags:
      - game-controller
      operationId: startGame
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: playerId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponseDto'
  /api/games/{gameId}/players/{playerId}/rollDice:
    post:
      tags:
        - game-controller
      operationId: rollDice
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: playerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameResponseDto"
            application/problem+json:
              schema:
                $ref: "#/components/schemas/GameResponseDto"
  /api/games/{gameId}/players/{playerId}/drawQuestion:
    post:
      tags:
        - game-controller
      operationId: drawQuestion
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: playerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameResponseDto"
            application/problem+json:
              schema:
                $ref: "#/components/schemas/GameResponseDto"
  /api/games/{gameId}/players/{playerId}/validate:
    post:
      tags:
        - game-controller
      operationId: validate
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: playerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
  /api/games/{gameId}/players/{playerId}/answer/{answerCode}:
    post:
      tags:
        - game-controller
      operationId: answer
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: playerId
          in: path
          required: true
          schema:
            type: string
        - name: answerCode
          in: path
          required: true
          schema:
            type: string
            enum:
              - A
              - B
              - C
              - D
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswerDto"
            application/problem+json:
              schema:
                $ref: "#/components/schemas/AnswerDto"
components:
  schemas:
    CreateGameRequestDto:
      type: object
      properties:
        gameName:
          type: string
        creator:
          $ref: '#/components/schemas/UserDto'
      required:
        - gameName
        - creator
    UserDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    GameResponseDto:
      required:
        - creator
        - currentPlayer
        - id
        - name
        - players
        - state
        - turn
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        state:
          $ref: "#/components/schemas/State"
        turn:
          type: integer
          format: int32
        creator:
          $ref: "#/components/schemas/PlayerDto"
        players:
          type: array
          items:
            $ref: "#/components/schemas/PlayerDto"
        currentPlayer:
          $ref: "#/components/schemas/PlayerDto"
        winner:
          $ref: "#/components/schemas/PlayerDto"
        currentQuestion:
          $ref: "#/components/schemas/QuestionDto"
        currentRoll:
          type: integer
          format: int32
        currentCategory:
          type: string
        currentAnswer:
          $ref: "#/components/schemas/AnswerDto"
    PlayerDto:
      required:
        - id
        - name
        - state
        - coinCount
        - location
        - gotOutOfPenaltyBox
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        coinCount:
          type: integer
          format: int32
        state:
          $ref: "#/components/schemas/State"
        location:
          type: integer
          format: int32
        gotOutOfPenaltyBox:
          type: boolean
    QuestionDto:
      required:
        - availableAnswers
        - id
        - questionText
      type: object
      properties:
        id:
          type: string
        questionText:
          type: string
        availableAnswers:
          type: object
          additionalProperties:
            type: string
    AnswerCode:
      type: string
      enum:
        - A
        - B
        - C
        - D
    AnswerDto:
      type: object
      required:
        - isCorrect
        - explanations
      properties:
        isCorrect:
          type: boolean
        explanations:
          type: string
    State:
      type: string
      enum:
        - CREATED
        - STARTED
        - ENDED
        - WAITING_FOR_DICE_ROLL
        - WAITING_FOR_ROLL_DICE_EVALUATION
        - IN_PENALTY_BOX
        - WAITING_TO_UPDATE_LOCATION
        - WAITING_TO_DRAW_1ST_QUESTION
        - WAITING_FOR_1ST_ANSWER
        - WAITING_FOR_1ST_ANSWER_EVALUATION
        - WAITING_TO_DRAW_2ND_QUESTION
        - WAITING_FOR_2ND_ANSWER
        - WAITING_FOR_2ND_ANSWER_EVALUATION
        - WAITING_TO_END_TURN_OR_GAME
        - WAITING_TO_VALIDATE_FIRST_CORRECT_ANSWER
        - WAITING_TO_VALIDATE_FIRST_INCORRECT_ANSWER
        - WAITING_TO_VALIDATE_SECOND_CORRECT_ANSWER
        - WAITING_TO_VALIDATE_SECOND_INCORRECT_ANSWER
        - WAITING_TO_VALIDATE_ODD_DICE_ROLL_FROM_PENALTY_BOX
        - WAITING_TO_VALIDATE_EVEN_DICE_ROLL_FROM_PENALTY_BOX
        - GAME_END