openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/games/{gameId}/logs:
    get:
      tags:
        - trivia-controller
      operationId: getGameLogs
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameLog'
components:
  schemas:
    GameLog:
      type: object
      properties:
        gameId:
          type: integer
          format: int32
        value:
          type: string
      required:
        - gameId
        - value